Repository ispp-2324-ocial/KB, pull requests merged in 2024-02, with the labels that each got.

#7 chore: formalize RFC process
  0000-template.md
  README.md
Labels: documentation

#8 fix: readme formatting
  README.md
Labels: enhancement

#15 docs: acta reunion frontend
  meetings/acta-02-22.md
Labels: frontend, documentation

#16 docs: trabajo semanal y organizacion presentacion
  meetings/acta-02-26.md
Labels: entire team

#19 Feedback 27/02
  feedback/feedback clase 27-02.md
Labels: documentation

#20 docs: acta clase y tareas
  meetings/acta-02-27.md
Labels: documentation
